repository_type: pipeline

nf_core_version: 3.2.1

lint:
  files_exist:
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/CONTRIBUTING.md
    - .github/.dockstore.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/email_template.txt
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/adaptivecard.json
    - assets/slackreport.json
    - assets/nf-core-measeq_logo_light.png
    - docs/images/nf-core-measeq_logo_light.png
    - docs/images/nf-core-measeq_logo_dark.png
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - assets/multiqc_config.yml
    - CODE_OF_CONDUCT.md
    - ro-crate-metadata.json
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .prettierignore
    - docs/README.md
    - LICENSE
  nextflow_config:
    - process.cpus
    - process.memory
    - process.time
    - custom_config
    - config_defaults:
        - params.custom_nextclade_dataset
    - params.custom_config_version
    - params.custom_config_base
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config: false
  readme:
    - nextflow_badge

template:
  org: phac-nml
  name: measeq
  description: Measles Sequencing and Analysis
  author: Darian Hole, Ahmed Abdalla, Molly Pratt
  version: 0.2.2
  force: true
  outdir: .
  skip_features:
    - github
    - igenomes
    - github_badges
    - nf_core_configs
    - email
    - adaptivecard
    - slackreport
    - seqera_platform
    - rocrate
    - vscode
  is_nfcore: false
